import assert from "node:assert";
import { type SourceFile, VariableDeclarationKind } from "ts-morph";
import type {
  LexiconArray,
  LexiconArrayItems,
  LexiconBlob,
  LexiconBoolean,
  LexiconBytes,
  LexiconCid,
  LexiconDocument,
  LexiconError,
  LexiconIndexer,
  LexiconInteger,
  LexiconObject,
  LexiconParameters,
  LexiconPayload,
  LexiconProcedure,
  LexiconQuery,
  LexiconRecord,
  LexiconRef,
  LexiconRefUnion,
  LexiconString,
  LexiconSubscription,
  LexiconToken,
  LexiconUnknown,
  MainLexiconDefinition,
  NamedLexiconDefinition,
} from "@atp/lex/document";

import {
  getPublicIdentifiers,
  RefResolver,
  type ResolvedRef,
} from "./ref-resolver.ts";
import { isSafeIdentifier } from "./ts-lang.ts";

export type LexDefBuilderOptions = {
  importExt?: string;
  lib?: string;
  allowLegacyBlobs?: boolean;
  pureAnnotations?: boolean;
};

type AnyDef = MainLexiconDefinition | NamedLexiconDefinition;
type DefsMap = Record<string, AnyDef | undefined>;

type MsgSchema =
  | LexiconRef
  | LexiconRefUnion
  | LexiconObject
  | undefined;

export class LexDefBuilder {
  private readonly refResolver: RefResolver;
  private static readonly BANNER =
    '/*\n * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.\n */';

  constructor(
    private readonly options: LexDefBuilderOptions,
    private readonly file: SourceFile,
    private readonly doc: LexiconDocument,
    indexer: LexiconIndexer,
  ) {
    this.refResolver = new RefResolver(doc, file, indexer, options);
  }

  private pure(code: string): string {
    return this.options.pureAnnotations ? markPure(code) : code;
  }

  async build(): Promise<void> {
    this.file.insertText(
      0,
      `${LexDefBuilder.BANNER}\n`,
    );

    this.file.addVariableStatement({
      declarationKind: VariableDeclarationKind.Const,
      declarations: [
        {
          name: "$nsid",
          initializer: JSON.stringify(this.doc.id),
        },
      ],
    });

    this.file.addExportDeclaration({
      namedExports: [{ name: "$nsid" }],
    });

    const defs = Object.keys(this.doc.defs);
    if (defs.length) {
      const moduleSpecifier = this.options.lib ?? "@atp/lex";
      this.file
        .addImportDeclaration({ moduleSpecifier })
        .addNamedImports([{ name: "l" }]);

      for (const hash of defs) {
        await this.addDef(hash);
      }
    }

    this.normalizeBannerSpacing();
  }

  private normalizeBannerSpacing(): void {
    const text = this.file.getFullText();
    const before = `${LexDefBuilder.BANNER}\n`;
    const after = `${LexDefBuilder.BANNER}\n\n`;

    if (text.startsWith(before) && !text.startsWith(after)) {
      this.file.replaceWithText(`${after}${text.slice(before.length)}`);
    }
  }

  private addUtils(definitions: Record<string, string | undefined>): void {
    const entries = Object.entries(definitions).filter(
      (e): e is [(typeof e)[0], string] => e[1] != null,
    );
    if (entries.length) {
      this.file.addVariableStatement({
        isExported: true,
        declarationKind: VariableDeclarationKind.Const,
        declarations: entries.map(([name, initializer]) => ({
          name,
          initializer,
        })),
      });
    }
  }

  private async addDef(hash: string): Promise<void> {
    const defsMap = this.doc.defs as unknown as DefsMap;
    const def = Object.hasOwn(this.doc.defs, hash) ? defsMap[hash] : null;
    if (def == null) return;

    switch (def.type) {
      case "procedure":
        return this.addProcedure(hash, def);
      case "query":
        return this.addQuery(hash, def);
      case "subscription":
        return this.addSubscription(hash, def);
      case "record":
        return this.addRecord(hash, def);
      case "token":
        return this.addToken(hash, def);
      case "object":
        return this.addObject(hash, def);
      case "array":
        return this.addArray(hash, def);
      default: {
        const containedDef = def as LexiconArray | LexiconArrayItems;
        await this.addSchema(hash, containedDef, {
          type: await this.compileContainedType(containedDef),
          schema: await this.compileContainedSchema(containedDef),
          validationUtils: true,
        });
      }
    }
  }

  private async addProcedure(
    hash: string,
    def: LexiconProcedure,
  ): Promise<void> {
    if (hash !== "main") {
      throw new Error(`Definition ${hash} cannot be of type ${def.type}`);
    }

    const ref = await this.compileXrpcRef(hash, def, {
      schema: async () =>
        this.pure(
          `l.procedure($nsid, ${await this
            .compileParamsSchema(def.parameters)}, ${await this.compilePayload(
              def.input,
            )}, ${await this.compilePayload(def.output)}${await this
            .compileErrors(def.errors)})`,
        ),
    });
    this.addMethodTypeStatements(ref, def);
    this.addUtils({
      $lxm: this.pure(`${ref.varName}.nsid`),
      $params: this.pure(`${ref.varName}.parameters`),
      $input: this.pure(`${ref.varName}.input`),
      $output: this.pure(`${ref.varName}.output`),
    });
  }

  private async addQuery(hash: string, def: LexiconQuery): Promise<void> {
    if (hash !== "main") {
      throw new Error(`Definition ${hash} cannot be of type ${def.type}`);
    }

    const ref = await this.compileXrpcRef(hash, def, {
      schema: async () =>
        this.pure(
          `l.query($nsid, ${await this
            .compileParamsSchema(def.parameters)}, ${await this.compilePayload(
              def.output,
            )}${await this.compileErrors(def.errors)})`,
        ),
    });
    this.addMethodTypeStatements(ref, def);
    this.addUtils({
      $lxm: this.pure(`${ref.varName}.nsid`),
      $params: this.pure(`${ref.varName}.parameters`),
      $output: this.pure(`${ref.varName}.output`),
    });
  }

  private async addSubscription(
    hash: string,
    def: LexiconSubscription,
  ): Promise<void> {
    if (hash !== "main") {
      throw new Error(`Definition ${hash} cannot be of type ${def.type}`);
    }

    const msgSchema = def.message?.schema as MsgSchema;
    let messageSchema: string;

    if (!msgSchema) {
      messageSchema = "undefined";
    } else if (msgSchema.type === "ref") {
      const { varName, typeName } = await this.refResolver.resolve(
        msgSchema.ref,
      );
      messageSchema = this.pure(
        `l.ref<${typeName}>(() => ${varName})`,
      );
    } else if (msgSchema.type === "union") {
      if (msgSchema.refs.length === 0 && msgSchema.closed) {
        messageSchema = this.pure("l.never()");
      } else {
        const refs = await Promise.all(
          msgSchema.refs.map(async (ref: string) => {
            const { varName, typeName } = await this.refResolver.resolve(ref);
            return this.pure(
              `l.typedRef<${typeName}>(() => ${varName})`,
            );
          }),
        );
        messageSchema = this.pure(
          `l.typedUnion([${refs.join(",")}], ${msgSchema.closed ?? false})`,
        );
      }
    } else {
      messageSchema = await this.compileObjectSchema(msgSchema);
    }

    const ref = await this.compileXrpcRef(hash, def, {
      schema: async () =>
        this.pure(
          `l.subscription($nsid, ${await this
            .compileParamsSchema(def.parameters)}, ${messageSchema}${await this
            .compileErrors(def.errors)})`,
        ),
    });
    this.addMethodTypeStatements(ref, def);
    this.addUtils({
      $lxm: this.pure(`${ref.varName}.nsid`),
      $params: this.pure(`${ref.varName}.parameters`),
      $message: this.pure(`${ref.varName}.message`),
    });
  }

  private compileXrpcRef(
    hash: string,
    def: { description?: string },
    opts: { schema: (ref: ResolvedRef) => Promise<string> },
  ): Promise<ResolvedRef> {
    return this.addSchema(hash, def, {
      schema: opts.schema,
      validationUtils: false,
    });
  }

  private addMethodTypeStatements(
    ref: ResolvedRef,
    def: LexiconProcedure | LexiconQuery | LexiconSubscription,
  ): void {
    this.file.addTypeAlias({
      isExported: true,
      name: "$Params",
      type: `l.InferMethodParams<typeof ${ref.varName}>`,
    });

    if (def.type === "procedure") {
      this.file.addTypeAlias({
        isExported: true,
        name: "$Input<B = l.BinaryData>",
        type: `l.InferMethodInput<typeof ${ref.varName}, B>`,
      });

      this.file.addTypeAlias({
        isExported: true,
        name: "$InputBody<B = l.BinaryData>",
        type: `l.InferMethodInputBody<typeof ${ref.varName}, B>`,
      });
    }

    if (def.type === "procedure" || def.type === "query") {
      this.file.addTypeAlias({
        isExported: true,
        name: "$Output<B = l.BinaryData>",
        type: `l.InferMethodOutput<typeof ${ref.varName}, B>`,
      });

      this.file.addTypeAlias({
        isExported: true,
        name: "$OutputBody<B = l.BinaryData>",
        type: `l.InferMethodOutputBody<typeof ${ref.varName}, B>`,
      });
    }

    if (def.type === "subscription") {
      this.file.addTypeAlias({
        isExported: true,
        name: "$Message",
        type: `l.InferSubscriptionMessage<typeof ${ref.varName}>`,
      });
    }
  }

  private async addRecord(hash: string, def: LexiconRecord): Promise<void> {
    const key = JSON.stringify(def.key);
    const objectSchema = await this.compileObjectSchema(def.record);
    const properties = await this.compilePropertiesTypes(def.record);

    await this.addSchema(hash, def, {
      type: `{ $type: string; ${properties.join(";")} }`,
      schema: this.pure(
        `l.record(${key}, $nsid, ${objectSchema})`,
      ),
      objectUtils: true,
      validationUtils: true,
    });
  }

  private async addObject(hash: string, def: LexiconObject): Promise<void> {
    const objectSchema = await this.compileObjectSchema(def);
    const properties = await this.compilePropertiesTypes(def);
    const $type = hash === "main" ? this.doc.id : `${this.doc.id}#${hash}`;
    properties.unshift(`$type?: ${JSON.stringify($type)}`);

    await this.addSchema(hash, def, {
      type: `{ ${properties.join(";")} }`,
      schemaType: (ref) =>
        `l.TypedObjectSchema<l.$TypeOf<${ref.typeName}>, l.Validator<Omit<${ref.typeName}, "$type">>>`,
      schema: (ref) =>
        this.pure(
          `l.typedObject<${ref.typeName}>($nsid, ${
            JSON.stringify(hash)
          }, ${objectSchema})`,
        ),
      objectUtils: true,
      validationUtils: true,
    });
  }

  private async addToken(hash: string, def: LexiconToken): Promise<void> {
    await this.addSchema(hash, def, {
      type: `l.$Type<typeof $nsid, ${JSON.stringify(hash)}>`,
      schema: this.pure(`l.token($nsid, ${JSON.stringify(hash)})`),
      validationUtils: true,
    });
  }

  private async addArray(hash: string, def: LexiconArray): Promise<void> {
    const itemSchema = await this.compileContainedSchema(def.items);
    const options = stringifyOptions(def, ["minLength", "maxLength"]);

    await this.addSchema(hash, def, {
      type: `(${await this.compileContainedType(def.items)})[]`,
      schema: this.pure(
        `l.array(${itemSchema}${options ? `, ${options}` : ""})`,
      ),
      validationUtils: true,
    });
  }

  private async addSchema(
    hash: string,
    def: { description?: string },
    {
      type,
      schema,
      schemaType,
      objectUtils,
      validationUtils,
    }: {
      type?: string | ((ref: ResolvedRef) => string);
      schema?: string | ((ref: ResolvedRef) => Promise<string> | string);
      schemaType?: string | ((ref: ResolvedRef) => string);
      objectUtils?: boolean;
      validationUtils?: boolean;
    },
  ): Promise<ResolvedRef> {
    const ref = await this.refResolver.resolveLocal(hash);
    const pub = getPublicIdentifiers(hash);

    assert(isSafeIdentifier(ref.varName), "Expected safe type identifier");
    assert(isSafeIdentifier(ref.typeName), "Expected safe type identifier");
    assert(isSafeIdentifier(pub.typeName), "Expected safe type identifier");

    if (type) {
      const typeStr = typeof type === "function" ? type(ref) : type;
      const typeStmt = this.file.addTypeAlias({
        name: ref.typeName,
        type: typeStr,
      });
      addJsDoc(typeStmt, def);

      this.file.addExportDeclaration({
        isTypeOnly: true,
        namedExports: [
          {
            name: ref.typeName,
            alias: ref.typeName === pub.typeName ? undefined : pub.typeName,
          },
        ],
      });
    }

    if (schema) {
      const schemaStr = typeof schema === "function"
        ? await schema(ref)
        : schema;
      const schemaTypeStr = schemaType
        ? typeof schemaType === "function" ? schemaType(ref) : schemaType
        : undefined;

      const constStmt = this.file.addVariableStatement({
        declarationKind: VariableDeclarationKind.Const,
        declarations: [{
          name: ref.varName,
          type: schemaTypeStr,
          initializer: schemaStr,
        }],
      });
      addJsDoc(constStmt, def);

      this.file.addExportDeclaration({
        namedExports: [
          {
            name: ref.varName,
            alias: ref.varName === pub.varName
              ? undefined
              : isSafeIdentifier(pub.varName)
              ? pub.varName
              : JSON.stringify(pub.varName),
          },
        ],
      });
    }

    if (hash === "main" && objectUtils) {
      this.addUtils({
        $isTypeOf: markPure(`${ref.varName}.isTypeOf.bind(${ref.varName})`),
        $build: markPure(`${ref.varName}.build.bind(${ref.varName})`),
        $type: markPure(`${ref.varName}.$type`),
      });
    }

    if (hash === "main" && validationUtils) {
      this.addUtils({
        $assert: markPure(`${ref.varName}.assert.bind(${ref.varName})`),
        $ifMatches: markPure(
          `${ref.varName}.ifMatches.bind(${ref.varName})`,
        ),
        $matches: markPure(`${ref.varName}.matches.bind(${ref.varName})`),
        $parse: markPure(`${ref.varName}.parse.bind(${ref.varName})`),
        $safeParse: markPure(
          `${ref.varName}.safeParse.bind(${ref.varName})`,
        ),
      });
    }

    return ref;
  }

  private async compilePayload(
    def: LexiconPayload | undefined,
  ): Promise<string> {
    if (!def) return this.pure("l.payload()");

    const schema = def.schema as
      | LexiconRef
      | LexiconRefUnion
      | LexiconObject
      | undefined;

    if (def.encoding === "application/json" && schema?.type === "object") {
      const properties = await this.compilePropertiesSchemas(schema);
      return this.pure(`l.jsonPayload({${properties.join(",")}})`);
    }

    const encodedEncoding = JSON.stringify(def.encoding);
    if (schema) {
      const bodySchema = await this.compileBodySchema(schema);
      return this.pure(`l.payload(${encodedEncoding}, ${bodySchema})`);
    }
    return this.pure(`l.payload(${encodedEncoding})`);
  }

  private compileBodySchema(
    def: LexiconRef | LexiconRefUnion | LexiconObject | undefined,
  ): Promise<string> {
    if (!def) return Promise.resolve("undefined");
    if (def.type === "object") return this.compileObjectSchema(def);
    return this.compileContainedSchema(def);
  }

  private async compileParamsSchema(
    def: LexiconParameters | undefined,
  ): Promise<string> {
    if (!def) return this.pure("l.params()");
    const properties = await this.compilePropertiesSchemas(def);
    return this.pure(
      properties.length === 0
        ? "l.params()"
        : `l.params({${properties.join(",")}})`,
    );
  }

  private compileErrors(defs?: readonly LexiconError[]): Promise<string> {
    if (!defs?.length) return Promise.resolve("");
    return Promise.resolve(`, ${JSON.stringify(defs.map((d) => d.name))}`);
  }

  private async compileObjectSchema(def: LexiconObject): Promise<string> {
    const properties = await this.compilePropertiesSchemas(def);
    return this.pure(`l.object({${properties.join(",")}})`);
  }

  private compilePropertiesSchemas(options: {
    properties: Record<string, LexiconArray | LexiconArrayItems>;
    required?: readonly string[];
    nullable?: readonly string[];
  }): Promise<string[]> {
    for (const opt of ["required", "nullable"] as const) {
      if (options[opt]) {
        for (const prop of options[opt]!) {
          if (!Object.hasOwn(options.properties, prop)) {
            throw new Error(`No schema found for ${opt} property "${prop}"`);
          }
        }
      }
    }
    return Promise.all(
      Object.entries(options.properties).map((entry) =>
        this.compilePropertyEntrySchema(entry, options)
      ),
    );
  }

  private compilePropertiesTypes(options: {
    properties: Record<string, LexiconArray | LexiconArrayItems>;
    required?: readonly string[];
    nullable?: readonly string[];
  }): Promise<string[]> {
    return Promise.all(
      Object.entries(options.properties).map((entry) =>
        this.compilePropertyEntryType(entry, options)
      ),
    );
  }

  private async compilePropertyEntrySchema(
    [key, def]: [string, LexiconArray | LexiconArrayItems],
    options: { required?: readonly string[]; nullable?: readonly string[] },
  ): Promise<string> {
    const isNullable = options.nullable?.includes(key);
    const isRequired = options.required?.includes(key);

    let schema = await this.compileContainedSchema(def);
    if (isNullable) schema = this.pure(`l.nullable(${schema})`);
    if (!isRequired) schema = this.pure(`l.optional(${schema})`);

    return `${JSON.stringify(key)}:${schema}`;
  }

  private async compilePropertyEntryType(
    [key, def]: [string, LexiconArray | LexiconArrayItems],
    options: { required?: readonly string[]; nullable?: readonly string[] },
  ): Promise<string> {
    const isNullable = options.nullable?.includes(key);
    const isRequired = options.required?.includes(key);

    const optional = isRequired ? "" : "?";
    const append = isNullable ? " | null" : "";
    const jsDoc = compileLeadingTrivia(def.description) ?? "";
    const name = JSON.stringify(key);
    const type = await this.compileContainedType(def);

    return `${jsDoc}${name}${optional}:${type}${append}`;
  }

  private compileContainedSchema(
    def: LexiconArray | LexiconArrayItems,
  ): Promise<string> {
    switch (def.type) {
      case "unknown":
        return Promise.resolve(this.compileUnknownSchema(def));
      case "boolean":
        return Promise.resolve(this.compileBooleanSchema(def));
      case "integer":
        return Promise.resolve(this.compileIntegerSchema(def));
      case "string":
        return Promise.resolve(this.compileStringSchema(def));
      case "bytes":
        return Promise.resolve(this.compileBytesSchema(def));
      case "blob":
        return Promise.resolve(this.compileBlobSchema(def));
      case "cid-link":
        return Promise.resolve(this.compileCidLinkSchema(def));
      case "ref":
        return this.compileRefSchema(def);
      case "union":
        return this.compileRefUnionSchema(def);
      case "array":
        return this.compileArraySchema(def);
      default:
        throw new Error(
          `Unsupported def type: ${(def as { type: string }).type}`,
        );
    }
  }

  private compileContainedType(
    def: LexiconArray | LexiconArrayItems,
  ): Promise<string> {
    switch (def.type) {
      case "unknown":
        return Promise.resolve(this.compileUnknownType(def));
      case "boolean":
        return Promise.resolve(this.compileBooleanType(def));
      case "integer":
        return Promise.resolve(this.compileIntegerType(def));
      case "string":
        return Promise.resolve(this.compileStringType(def));
      case "bytes":
        return Promise.resolve(this.compileBytesType(def));
      case "blob":
        return Promise.resolve(this.compileBlobType(def));
      case "cid-link":
        return Promise.resolve(this.compileCidLinkType(def));
      case "ref":
        return this.compileRefType(def);
      case "union":
        return this.compileRefUnionType(def);
      case "array":
        return this.compileArrayType(def);
      default:
        throw new Error(
          `Unsupported def type: ${(def as { type: string }).type}`,
        );
    }
  }

  private compileArraySchema(def: LexiconArray): Promise<string> {
    return this.compileContainedSchema(def.items).then((itemSchema) => {
      const options = stringifyOptions(def, ["minLength", "maxLength"]);
      return this.pure(
        `l.array(${itemSchema}${options ? `, ${options}` : ""})`,
      );
    });
  }

  private async compileArrayType(def: LexiconArray): Promise<string> {
    return `(${await this.compileContainedType(def.items)})[]`;
  }

  private compileUnknownSchema(_def: LexiconUnknown): string {
    return this.pure("l.unknownObject()");
  }

  private compileUnknownType(_def: LexiconUnknown): string {
    return "l.UnknownObject";
  }

  private compileBooleanSchema(def: LexiconBoolean): string {
    if (hasConst(def)) return this.compileConstSchema(def);
    const options = stringifyOptions(def, ["default"]);
    return this.pure(`l.boolean(${options})`);
  }

  private compileBooleanType(def: LexiconBoolean): string {
    if (hasConst(def)) return this.compileConstType(def);
    return "boolean";
  }

  private compileIntegerSchema(def: LexiconInteger): string {
    if (hasConst(def)) return this.compileConstSchema(def);
    if (hasEnum(def)) return this.compileEnumSchema(def);
    const options = stringifyOptions(def, ["default", "maximum", "minimum"]);
    return this.pure(`l.integer(${options})`);
  }

  private compileIntegerType(def: LexiconInteger): string {
    if (hasConst(def)) return this.compileConstType(def);
    if (hasEnum(def)) return this.compileEnumType(def);
    return "number";
  }

  private compileStringSchema(def: LexiconString): string {
    if (hasConst(def)) return this.compileConstSchema(def);
    if (hasEnum(def)) return this.compileEnumSchema(def);
    const options = stringifyOptions(def, [
      "default",
      "format",
      "maxGraphemes",
      "minGraphemes",
      "maxLength",
      "minLength",
    ]);
    return this.pure(`l.string(${options})`);
  }

  private compileStringType(def: LexiconString): string {
    if (hasConst(def)) return this.compileConstType(def);
    if (hasEnum(def)) return this.compileEnumType(def);

    switch (def.format) {
      case undefined:
        break;
      case "datetime":
        return "l.DatetimeString";
      case "uri":
        return "l.UriString";
      case "at-uri":
        return "l.AtUriString";
      case "did":
        return "l.DidString";
      case "handle":
        return "l.HandleString";
      case "at-identifier":
        return "l.AtIdentifierString";
      case "nsid":
        return "l.NsidString";
      case "tid":
        return "l.TidString";
      case "cid":
        return "l.CidString";
      case "language":
        return "l.LanguageString";
      case "record-key":
        return "l.RecordKeyString";
      default:
        throw new Error(`Unknown string format: ${def.format}`);
    }

    if (def.knownValues?.length) {
      return (
        def.knownValues.map((v) => JSON.stringify(v)).join(" | ") +
        " | l.UnknownString"
      );
    }

    return "string";
  }

  private compileBytesSchema(def: LexiconBytes): string {
    const options = stringifyOptions(def, ["minLength", "maxLength"]);
    return this.pure(`l.bytes(${options})`);
  }

  private compileBytesType(_def: LexiconBytes): string {
    return "Uint8Array";
  }

  private compileBlobSchema(def: LexiconBlob): string {
    const opts = {
      ...def,
      allowLegacy: this.options.allowLegacyBlobs === true,
    };
    const options = stringifyOptions(opts, [
      "maxSize",
      "accept",
      "allowLegacy",
    ]);
    return this.pure(`l.blob(${options})`);
  }

  private compileBlobType(_def: LexiconBlob): string {
    return this.options.allowLegacyBlobs
      ? "l.BlobRef | l.LegacyBlobRef"
      : "l.BlobRef";
  }

  private compileCidLinkSchema(_def: LexiconCid): string {
    return this.pure("l.cidLink()");
  }

  private compileCidLinkType(_def: LexiconCid): string {
    return "l.Cid";
  }

  private async compileRefSchema(def: LexiconRef): Promise<string> {
    const { varName, typeName } = await this.refResolver.resolve(def.ref);
    return this.pure(`l.ref<${typeName}>(() => ${varName})`);
  }

  private async compileRefType(def: LexiconRef): Promise<string> {
    const ref = await this.refResolver.resolve(def.ref);
    return ref.typeName;
  }

  private async compileRefUnionSchema(def: LexiconRefUnion): Promise<string> {
    if (def.refs.length === 0 && def.closed) {
      return this.pure("l.never()");
    }

    const refs = await Promise.all(
      def.refs.map(async (ref) => {
        const { varName, typeName } = await this.refResolver.resolve(ref);
        return this.pure(
          `l.typedRef<${typeName}>(() => ${varName})`,
        );
      }),
    );

    return this.pure(
      `l.typedUnion([${refs.join(",")}], ${def.closed ?? false})`,
    );
  }

  private async compileRefUnionType(def: LexiconRefUnion): Promise<string> {
    const types = await Promise.all(
      def.refs.map(async (ref) => {
        const { typeName } = await this.refResolver.resolve(ref);
        return `l.TypedRef<${typeName}>`;
      }),
    );
    if (!def.closed) types.push("l.TypedObject");
    return types.join(" | ") || "never";
  }

  private compileConstSchema<T extends null | number | string | boolean>(
    def: { const: T; enum?: readonly T[]; default?: T },
  ): string {
    if (hasEnum(def) && !def.enum.includes(def.const)) {
      return this.pure("l.never()");
    }
    const options = stringifyOptions(def, ["default"]);
    return this.pure(
      `l.literal(${JSON.stringify(def.const)}${options ? `, ${options}` : ""})`,
    );
  }

  private compileConstType<T extends null | number | string | boolean>(
    def: { const: T; enum?: readonly T[] },
  ): string {
    if (hasEnum(def) && !def.enum.includes(def.const)) return "never";
    return JSON.stringify(def.const);
  }

  private compileEnumSchema<T extends null | number | string>(def: {
    enum: readonly T[];
    default?: T;
  }): string {
    if (def.enum.length === 0) return this.pure("l.never()");
    if (def.enum.length === 1 && def.default === undefined) {
      return this.pure(`l.literal(${JSON.stringify(def.enum[0])})`);
    }
    const options = stringifyOptions(def, ["default"]);
    return this.pure(
      `l.enum(${JSON.stringify(def.enum)}${options ? `, ${options}` : ""})`,
    );
  }

  private compileEnumType<T extends null | number | string>(def: {
    enum: readonly T[];
  }): string {
    return def.enum.map((v) => JSON.stringify(v)).join(" | ") || "never";
  }
}

function parseDescription(description: string): {
  description: string;
  deprecated: boolean | string;
} {
  if (/deprecated/i.test(description)) {
    const deprecationMatch = description.match(
      /(\s*deprecated\s*(?:--?|:)?\s*([^-]*)(?:-+)?)/i,
    );
    if (deprecationMatch) {
      const [, match, deprecationNotice] = deprecationMatch;
      return {
        description: description.replace(match, "").trim(),
        deprecated: deprecationNotice?.trim() || true,
      };
    }
    return { description: description.trim(), deprecated: true };
  }
  return { description: description.trim(), deprecated: false };
}

function compileLeadingTrivia(description?: string): string | undefined {
  if (!description) return undefined;
  return `\n\n/**${compileJsDoc(description).replaceAll("\n", "\n * ")}\n */\n`;
}

function addJsDoc(
  declaration: { addJsDoc: (text: string) => void },
  def?: { description?: string },
): void {
  if (def?.description) {
    declaration.addJsDoc(compileJsDoc(def.description));
  }
}

function compileJsDoc(description: string): string {
  const parsed = parseDescription(description);
  return `\n${parsed.description}${
    !parsed.deprecated ? "" : (parsed.description ? "\n\n" : "") +
      (parsed.deprecated === true
        ? "@deprecated"
        : `@deprecated ${parsed.deprecated}`)
  }`;
}

function stringifyOptions<O extends Record<string, unknown>>(
  obj: O,
  include?: (keyof O)[],
): string {
  const filtered = Object.entries(obj).filter(
    ([k, v]) =>
      v !== undefined &&
      v !== null &&
      (!include || include.includes(k as keyof O)),
  );
  return filtered.length ? JSON.stringify(Object.fromEntries(filtered)) : "";
}

function hasConst<T extends { const?: unknown }>(
  def: T,
): def is T & { const: NonNullable<T["const"]> } {
  return def.const != null;
}

function hasEnum<T extends { enum?: readonly unknown[] }>(
  def: T,
): def is T & { enum: unknown[] } {
  return def.enum != null;
}

function markPure<T extends string>(v: T): `/*#__PURE__*/ ${T}` {
  return `/*#__PURE__*/ ${v}`;
}
