name: Check

on:
  pull_request:
    branches:
      - main

jobs:
  ok:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          cache: true
          deno-version: 2.x

      - name: Lint
        run: deno lint

      - name: Format
        run: deno fmt --check

      - name: Test
        run: deno test -P
