name: workspace publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          cache: true

      - name: Format
        run: deno fmt --check

      - name: Test
        run: deno test -A

      - name: Publish to JSR
        run: deno publish
