import { assert, assertRejects, assertStringIncludes } from "@std/assert";
import { Project } from "ts-morph";
import {
  type LexiconDocument,
  lexiconDocumentSchema,
  type LexiconIndexer,
} from "@atp/lex/document";
import { LexDefBuilder } from "../builder/def-builder.ts";

class DummyIndexer implements LexiconIndexer, AsyncIterable<LexiconDocument> {
  readonly #docs: Map<string, LexiconDocument>;

  constructor(docs: readonly LexiconDocument[]) {
    this.#docs = new Map(docs.map((doc) => [doc.id, doc]));
  }

  async get(id: string): Promise<LexiconDocument> {
    const doc = this.#docs.get(id);
    if (!doc) {
      throw new Error(`Document not found: ${id}`);
    }
    return doc;
  }

  async *[Symbol.asyncIterator](): AsyncIterator<LexiconDocument> {
    for (const doc of this.#docs.values()) {
      yield doc;
    }
  }
}

Deno.test("query generation uses method helpers and jsonPayload", async () => {
  const docs: LexiconDocument[] = [
    lexiconDocumentSchema.parse({
      lexicon: 1,
      id: "app.bsky.feed.getPosts",
      defs: {
        main: {
          type: "query",
          parameters: {
            type: "params",
            required: ["uris"],
            properties: {
              uris: {
                type: "array",
                items: { type: "string", format: "at-uri" },
                maxLength: 25,
              },
            },
          },
          output: {
            encoding: "application/json",
            schema: {
              type: "object",
              required: ["posts"],
              properties: {
                posts: {
                  type: "array",
                  items: { type: "ref", ref: "app.bsky.feed.defs#postView" },
                },
              },
            },
          },
        },
      },
    }),
    lexiconDocumentSchema.parse({
      lexicon: 1,
      id: "app.bsky.feed.defs",
      defs: {
        postView: {
          type: "object",
          required: [],
          properties: {},
        },
      },
    }),
  ];

  const project = new Project({ useInMemoryFileSystem: true });
  const file = project.createSourceFile("/app/bsky/feed/getPosts.defs.ts");
  const indexer = new DummyIndexer(docs);
  const builder = new LexDefBuilder({}, file, docs[0], indexer);
  await builder.build();

  const output = file.getFullText();
  assertStringIncludes(
    output,
    'THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.',
  );
  assertStringIncludes(
    output,
    ' */\n\nimport { l } from "@atp/lex";',
  );
  assertStringIncludes(
    output,
    'const $nsid = "app.bsky.feed.getPosts";',
  );
  assertStringIncludes(output, "const main = l.query($nsid,");
  assertStringIncludes(output, "l.jsonPayload({");
  assertStringIncludes(
    output,
    "export type $Params = l.InferMethodParams<typeof main>;",
  );
  assertStringIncludes(
    output,
    "export type $Output<B = l.BinaryData> = l.InferMethodOutput<typeof main, B>;",
  );
  assertStringIncludes(output, "export const $lxm = main.nsid,");
  assertStringIncludes(output, "$params = main.parameters,");
  assertStringIncludes(output, "$output = main.output;");
  assert(!output.includes("as any"));
});

Deno.test("xrpc definitions must be named main", async () => {
  const doc = {
    lexicon: 1,
    id: "com.example.bad",
    defs: {
      custom: {
        type: "query",
        parameters: { type: "params", properties: {} },
        output: { encoding: "application/json" },
      },
    },
  } as unknown as LexiconDocument;
  const project = new Project({ useInMemoryFileSystem: true });
  const file = project.createSourceFile("/com/example/bad.defs.ts");
  const indexer = new DummyIndexer([doc]);
  const builder = new LexDefBuilder({}, file, doc, indexer);

  await assertRejects(
    async () => await builder.build(),
    Error,
    "Definition custom cannot be of type query",
  );
});

Deno.test("object defs generate typedObject with $type metadata", async () => {
  const doc = lexiconDocumentSchema.parse({
    lexicon: 1,
    id: "com.example.account.history",
    defs: {
      main: {
        type: "query",
        output: {
          encoding: "application/json",
          schema: {
            type: "object",
            required: ["event"],
            properties: {
              event: { type: "ref", ref: "#event" },
            },
          },
        },
      },
      event: {
        type: "object",
        required: ["details"],
        properties: {
          details: {
            type: "union",
            refs: ["#accountCreated"],
            closed: true,
          },
        },
      },
      accountCreated: {
        type: "object",
        properties: {
          email: { type: "string" },
        },
      },
    },
  });

  const project = new Project({ useInMemoryFileSystem: true });
  const file = project.createSourceFile("/com/example/account/history.defs.ts");
  const indexer = new DummyIndexer([doc]);
  const builder = new LexDefBuilder({}, file, doc, indexer);
  await builder.build();

  const output = file.getFullText();
  assertStringIncludes(
    output,
    '$type?: "com.example.account.history#accountCreated"',
  );
  assertStringIncludes(
    output,
    'const accountCreated: l.TypedObjectSchema<l.$TypeOf<AccountCreated>, l.Validator<Omit<AccountCreated, "$type">>> = l.typedObject<AccountCreated>($nsid, "accountCreated",',
  );
  assertStringIncludes(
    output,
    'const event: l.TypedObjectSchema<l.$TypeOf<Event>, l.Validator<Omit<Event, "$type">>> = l.typedObject<Event>(',
  );
});
